runtime: php55
api_version: 1
threadsafe: true

runtime_config:
  document_root: web

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: index.php

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

# [START env]
env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:host=localhost;dbname=pictures
  MYSQL_USER: test-user
  MYSQL_PASSWORD: test
  GPROJECT_ID: assistenzsose2018example
# [END env]
