runtime: php55
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /.*
  script: index.php

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/assistenzsose2018example:europe-west3:exampledb;dbname=pictures
  MYSQL_USER: test-user
  MYSQL_PASSWORD: test
  GPROJECT_ID: assistenzsose2018example